import Head from "next/head";
import { Container } from "@mui/material";
import HeaderMenu from "@/src/companents/Header-menu";
import { QueryClient, QueryClientProvider } from "react-query";
import{SwiperHeader} from "@/src/companents/Swiper"

const queryClient = new QueryClient();

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Container maxWidth="lg">
          <HeaderMenu />
          <SwiperHeader />
        </Container>
      </QueryClientProvider>
    </>
  );
}
